require_relative 'randomizers/randomizer'
require_relative 'randomizers/numeric_randomizer'
require_relative 'randomizers/coin'
require_relative 'randomizers/die'
require_relative 'randomizers/fudge_die'
